[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "docswasnakerid"
authors = [{name = "Wasnaker.ID", email = "wasnaker.id@gmail.com"}]
dynamic = ["version", "description"]
